### ISSUE TITLE
[Suggestion] Add Charm and Charmonium

### ISSUE THREAD

**Issue by Merith-TK** [ZekeSmith/HexMC-Modpack#12]
https://modrinth.com/mod/charm
https://modrinth.com/mod/charmonium

**Comment by DioEgizio** [comment]
charm has a lot of compat issues in 1.18.2

**Comment by Merith-TK** [comment]
I personally have not ran into this myself, however if the compat issues
are recipes, I am familiar with kubejs

**Comment by DioEgizio** [comment]
Just take a look to https://github.com/svenhjol/Charm/issues

**Comment by Merith-TK** [comment]
huh, okay then
